"""add manufacture_cost and shipping_cost to orders

Revision ID: 0d86bfe6a8de
Revises: 7484932f0e0c
Create Date: 2026-02-13 18:11:54.651446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d86bfe6a8de'
down_revision: Union[str, Sequence[str], None] = '7484932f0e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('manufacturing_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('transport_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'transport_cost')
    op.drop_column('order_items', 'manufacturing_cost')
    # ### end Alembic commands ###
